# Generated by Django 5.2.3 on 2025-06-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Images'), ('video', 'Video'), ('file', 'Files'), ('mixed', 'Mixed')], default='none', max_length=10),
        ),
    ]
