# Generated by Django 5.2.3 on 2025-06-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postfile_file_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('image', 'Images'), ('video', 'Video'), ('file', 'Files'), ('mixed', 'Mixed')], default='none', max_length=10, null=True),
        ),
    ]
