# Generated by Django 5.2.3 on 2025-06-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='post_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='post_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='post_videos/%Y/%m/%d/'),
        ),
    ]
