# Generated by Django 5.2.3 on 2025-06-29 10:11

from django.db import migrations
from django.db.models import F

def create_custom_users(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    User = apps.get_model('auth', 'User')
    
    # Create CustomUser objects for all existing users
    for user in User.objects.all():
        CustomUser.objects.create(user=user, role='student')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_custom_users),
    ]
