# Generated by Django 5.2.3 on 2025-07-01 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment_updated_at'),
        ('user_notifications', '0002_notification_deleted_at_notification_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient', 'post', 'notification_type'), name='unique_notification'),
        ),
    ]
