# Generated by Django 5.2.3 on 2025-07-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0003_notification_unique_notification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_notification',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='user_notifi_recipie_1ce727_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='user_notifi_created_6c476a_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='user_notifi_deleted_e3a93e_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='user_notifi_group_i_e6d013_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
    ]
